"""
Django settings for errorsupportportal project.

Generated by 'django-admin startproject' using Django 2.1.15.

For more information on this file, see
https://docs.djangoproject.com/en/2.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/2.1/ref/settings/
"""

import os

# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/2.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = "fhld4r*w&ix1i#8cv_s^m#9^23bc)yunv2m1viy_s(yg)g+rj="

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

#Specify where this project is allowed to run
ALLOWED_HOSTS = [
    "127.0.0.1",
    "localhost",
    ".np-ocp-openstack.prci.com",
    ".ocp-openstack.prci.com",
]


# Application definitions
# Specify which apps are a part of the project
# Hint: usually the apps you build go first, so that any 
# customization of admin/auth templates take precendence
# if there are two versions of the same template, file, etc.
INSTALLED_APPS = [
    "portal.apps.PortalConfig", #takes first precedence
    "django.contrib.admin", 
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",   #last precedence
]

MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
]

# Where the project level URLs file is stored
ROOT_URLCONF = "errorsupportportal.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [os.path.join(BASE_DIR, "templates")], #Tell Django where to look for templates, in search order
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.debug",
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]

WSGI_APPLICATION = "errorsupportportal.wsgi.application"


# Database
# https://docs.djangoproject.com/en/2.1/ref/settings/#databases
# Tell Django which database backend to use
DATABASES = {
    "default": {
        "ENGINE": "sql_server.pyodbc", # database backend engine to use (should be an installed python package)
        "HOST": "scbiss21.proghsz.com", # 
        "PORT": "1433",
        "NAME": "BISSCRMCOMDIM",
        "TIME_ZONE": "EST",
        "Trusted_Connection": "yes",
    }
}


# Password validation
# https://docs.djangoproject.com/en/2.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]


# Internationalization
# https://docs.djangoproject.com/en/2.1/topics/i18n/

LANGUAGE_CODE = "en-us"

TIME_ZONE = "UTC"

USE_I18N = True

USE_L10N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/2.1/howto/static-files/

# MEDIA_URL = "/images/"

STATICFILES_DIRS = [os.path.join(BASE_DIR, "portal/staticimports")] # where Django will look for static files to collect
STATIC_ROOT = os.path.join(BASE_DIR, "static") # where Django will put all the collected static files
STATIC_URL = "/static/" # where to reference static files in templates ex. <img src="{% static 'images/CRM-BI_Logo_White.svg' %}">